### PR TITLE
Port to TypeScript, add fpmount functionality.

### PR DESCRIPTION
**Pull request by LindirQuenya**
This removes the need to include fpmount or python in FP.

### CODE REVIEW

**Comment by XXLuigiMario** [comment]
Consider adding the typings directory from the launcher repo as a submodule instead of copying it into the source tree.
You also need to add package-lock.json to .gitignore

**Comment by jbmagination** [comment]
Why should `package-lock.json` be gitignored? The whole point of the file is that it is committed to a repository ([source](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json))

**Comment by LindirQuenya** [comment]
I agree - the point of the `package-lock.json` is to ensure that everyone builds this with the exact same versions of all the dependencies. I think it would be better to leave it in.

**Comment by XXLuigiMario** [comment]
@jbmagination @LindirQuenya I must admit the name "lock" had me thinking it was little more than a lock file that's generated by npm. However, after some research, it doesn't seem to be all that useful. It seems to be aimed at replicable builds in CI environments. "npm install" itself doesn't even use it, and in fact overwrites it on each use. You must specifically use "npm ci". ([source](https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json))

While I understand what it does, I fail to see how it's useful in our case. Given the size and scope of this project, why should we care about tracking versions of dependencies of dependencies? Most other package managers don't even offer this (see: pip, maven, etc.). All it would seem to be good for in our case is dirtying up commit diffs. I believe asking to check in a 10k+ line generated file should be unacceptable unless there's a very good reason to do so.

**Comment by LindirQuenya** [comment]
The new typings are up. This can be merged.

**Comment by XXLuigiMario** [comment]
Shall FPMount become something of the past. Thanks for your work :smile:

**Comment by XXLuigiMario** [comment]
For future readers that may stumble into this. The "nudge" functionality is implemented in order to work around a QEMU bug that intermittently stalls a QMP connection indefinitely on Windows. It is unclear what causes this, but this appears to work :shrug:

**Pull request merged**
